// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMqpFqrVTzVPE7yYW4yyDZIOQX8ijxMDQ',
    appId: '1:873033576605:web:3ca98db111ab0d2663e474',
    messagingSenderId: '873033576605',
    projectId: 'kabar-news-6ba82',
    authDomain: 'kabar-news-6ba82.firebaseapp.com',
    storageBucket: 'kabar-news-6ba82.firebasestorage.app',
    measurementId: 'G-BR63Z7G4YJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBat2sLpBMvTYZKxljhRvUa-Znm5Lo9MpA',
    appId: '1:873033576605:android:1d50d00bbbaa600b63e474',
    messagingSenderId: '873033576605',
    projectId: 'kabar-news-6ba82',
    storageBucket: 'kabar-news-6ba82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPMAGKTIZCZnCii8e94iEczw1sk2Pe-SU',
    appId: '1:873033576605:ios:2a3200a41a8c71f163e474',
    messagingSenderId: '873033576605',
    projectId: 'kabar-news-6ba82',
    storageBucket: 'kabar-news-6ba82.firebasestorage.app',
    iosClientId: '873033576605-rp12ek0kurqbrgjtm3co5kg5jhg267h8.apps.googleusercontent.com',
    iosBundleId: 'com.example.kabarNews',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPMAGKTIZCZnCii8e94iEczw1sk2Pe-SU',
    appId: '1:873033576605:ios:2a3200a41a8c71f163e474',
    messagingSenderId: '873033576605',
    projectId: 'kabar-news-6ba82',
    storageBucket: 'kabar-news-6ba82.firebasestorage.app',
    iosClientId: '873033576605-rp12ek0kurqbrgjtm3co5kg5jhg267h8.apps.googleusercontent.com',
    iosBundleId: 'com.example.kabarNews',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMqpFqrVTzVPE7yYW4yyDZIOQX8ijxMDQ',
    appId: '1:873033576605:web:613b608488a3fe5b63e474',
    messagingSenderId: '873033576605',
    projectId: 'kabar-news-6ba82',
    authDomain: 'kabar-news-6ba82.firebaseapp.com',
    storageBucket: 'kabar-news-6ba82.firebasestorage.app',
    measurementId: 'G-6GWDXP9S7D',
  );
}
